### ISSUE TITLE
NPE while playing with ingame config on forge 13.20.0.2282

### ISSUE THREAD

**Issue by Baalith** [KidsDontPlay/Harvesting-Animals#2]
Here's the part of the log which shows the error while playing with the ingame config (mods button on main menu)

[22:06:31] [Client thread/ERROR] [FML]: There was a critical issue trying to build the config GUI for ceanimals
java.lang.NullPointerException
	at net.minecraftforge.common.config.ConfigManager.getModConfigClasses(ConfigManager.java:205) ~[ConfigManager.class:?]
	at net.minecraftforge.fml.client.config.GuiConfig.<init>(GuiConfig.java:95) ~[GuiConfig.class:?]
	at net.minecraftforge.fml.client.DefaultGuiFactory.createConfigGui(DefaultGuiFactory.java:37) ~[DefaultGuiFactory.class:?]
	at net.minecraftforge.fml.client.GuiModList.func_146284_a(GuiModList.java:288) [GuiModList.class:?]
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:454) [bho.class:?]
	at net.minecraftforge.fml.client.GuiModList.func_73864_a(GuiModList.java:199) [GuiModList.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:544) [bho.class:?]
	at net.minecraftforge.fml.client.GuiModList.func_146274_d(GuiModList.java:337) [GuiModList.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512) [bho.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1695) [bes.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056) [bes.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372) [bes.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[22:06:32] [Client thread/ERROR] [FML]: There was a critical issue trying to build the config GUI for ceanimals
java.lang.NullPointerException
	at net.minecraftforge.common.config.ConfigManager.getModConfigClasses(ConfigManager.java:205) ~[ConfigManager.class:?]
	at net.minecraftforge.fml.client.config.GuiConfig.<init>(GuiConfig.java:95) ~[GuiConfig.class:?]
	at net.minecraftforge.fml.client.DefaultGuiFactory.createConfigGui(DefaultGuiFactory.java:37) ~[DefaultGuiFactory.class:?]
	at net.minecraftforge.fml.client.GuiModList.func_146284_a(GuiModList.java:288) [GuiModList.class:?]
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:454) [bho.class:?]
	at net.minecraftforge.fml.client.GuiModList.func_73864_a(GuiModList.java:199) [GuiModList.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:544) [bho.class:?]
	at net.minecraftforge.fml.client.GuiModList.func_146274_d(GuiModList.java:337) [GuiModList.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512) [bho.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1695) [bes.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056) [bes.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372) [bes.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

I hope it helps to track down the issue.

Best regards, Baalith

**Comment by KidsDontPlay** [comment]
did the game crash?

**Comment by Baalith** [comment]
Nope, ditn't crash. I just thought it's worth to report to avoid error logspam 👍

**Comment by KidsDontPlay** [comment]
~~seems like a issue with forge~~
yap, It's a forge bug
